# Generated by Django 4.0.3 on 2022-09-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=150, verbose_name='City name')),
                ('timezone', models.CharField(blank=True, max_length=10, verbose_name='Timezone')),
                ('longitude', models.CharField(blank=True, max_length=12, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=12, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(blank=True, choices=[('1H', '1H'), ('3H', '3H'), ('6H', '6H'), ('12H', '12H'), ('24H', '24H')], max_length=3, null=True, verbose_name='Interval')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(blank=True, max_length=150, verbose_name='Weather')),
                ('temp', models.CharField(blank=True, max_length=5, verbose_name='Temperature')),
                ('humidity', models.CharField(blank=True, max_length=5, verbose_name='Humidity')),
                ('pressure', models.CharField(blank=True, max_length=5, verbose_name='Pressure')),
                ('temp_min', models.CharField(blank=True, max_length=5, verbose_name='Min temperature')),
                ('temp_max', models.CharField(blank=True, max_length=5, verbose_name='Max temperature')),
                ('visibility', models.CharField(blank=True, max_length=20, verbose_name='Visibility')),
                ('wind_speed', models.CharField(blank=True, max_length=10, verbose_name='Wind speed')),
                ('clouds', models.CharField(blank=True, max_length=35, verbose_name='Clouds')),
                ('sunrise', models.TimeField(blank=True, max_length=35, verbose_name='Sunrise')),
                ('sunset', models.TimeField(blank=True, max_length=35, verbose_name='Sunset')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.subscriptions', verbose_name='Subscription'),
        ),
    ]
