# Generated by Django 4.0.3 on 2022-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='subscription',
        ),
        migrations.AddField(
            model_name='city',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='weather.subscriptions'),
        ),
    ]
